[package]
name = "exercicios_rust"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "shadowing_execs"
path = "src/exercicios/shadowing_execs.rs"

[[bin]]
name = "shadowing_execs_2"
path = "src/exercicios/shadowing_execs_2.rs"